stages:
  - build


build-image-job:
  stage: build
  image: docker:27.3
  services:
    - docker:27.3:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER gitlab.crja72.ru:5050 --password-stdin
    - docker build -t gitlab.crja72.ru:5050/django/2024/autumn/course/projects/team-13 .
    - docker push gitlab.crja72.ru:5050/django/2024/autumn/course/projects/team-13