stages:
  - linting
  - test

variables:
  PYTHON_VERSION: "3.11"
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - apk add --no-cache make
    - make black-check

isort:
  stage: linting
  image: python:${PYTHON_VERSION}
  needs:
    - black
  script:
    - make isort-check

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  needs:
    - isort
  script:
    - apk add --no-cache make
    - make check-flake8-requirements
    - make flake8-check

test:
  stage: test
  image: docker:20.10.24
  services:
    - name: docker:20.10.24-dind
      alias: docker
  script:
    - apk add --no-cache docker-compose make
    - docker info
    - docker-compose up -d
    - make check-test-requirements
    - make test

