stages:
  - flake8
  - django_tests


flake8-check:
  stage: flake8
  image: python:3.10
  before_script:
    - pip install -r requirements/test.txt
  script:
    - flake8 .

django_tests:
  stage: django_tests
  image: python:3.10
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements/prod.txt
  script:
    - cd egame
    - python3 manage.py test
