stages:
  - linting
  - test

variables:
  PYTHON_VERSION: "3.11"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - apk add --no-cache make
    - make black-check

isort:
  stage: linting
  image: python:${PYTHON_VERSION}
  needs:
    - black
  script:
    - make isort-check

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  needs:
    - isort
  script:
    - apk add --no-cache make
    - make check-flake8-requirements
    - make flake8-check

test:
  stage: test
  image: docker:24
  services:
    - name: docker:24-dind
      alias: docker
      command: ["--host=tcp://0.0.0.0:2375"]
  before_script:
    - apk add --no-cache docker-compose make iputils curl
    - ping -c 4 docker || echo "Cannot resolve docker"
    - nslookup docker || echo "NSLookup failed"
    - until docker info; do sleep 1; done
    - docker-compose version
  script:
    - docker-compose down
    - docker-compose pull redis
    - docker-compose up -d redis
    - make check-test-requirements
    - make test
  after_script:
    - docker-compose down

