stages:
  - build
  - linting
  - test

variables:
  DOCKER_IMAGE: my-backend-image
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

build-job:
  stage: build
  image: docker:latest
  script:
    - docker build --cache-from=$DOCKER_IMAGE -t $DOCKER_IMAGE .

black-job:
  stage: linting
  script:
    - docker run --rm $DOCKER_IMAGE black-check

isort-job:
  stage: linting
  script:
    - docker run --rm $DOCKER_IMAGE isort-check

flake8-job:
  stage: linting
  script:
    - docker run --rm $DOCKER_IMAGE make check-flake8-requirements
    - docker run --rm $DOCKER_IMAGE make flake8-check

test-job:
  stage: test
  script:
    - docker run --rm $DOCKER_IMAGE make check-test-requirements
    - docker run --rm $DOCKER_IMAGE make test

